### ISSUE TITLE
Non-systemd linux boxes: fail nicer or handle better.

### ISSUE THREAD

**Issue by mjsir911** [karlicoss/promnesia#117]
Hello,

On my non-systemd linux machine when I run `promnesia install-server` it complains with a pretty ugly traceback:

```
Writing launch script to /home/msirabella/.config/systemd/user/promnesia.service
Something has gone wrong... you might want to use 'journalctl --user -u promnesia.service' to investigate
Traceback (most recent call last):
  File "/usr/bin/promnesia", line 11, in <module>
    load_entry_point('promnesia==0.11.20200605', 'console_scripts', 'promnesia')()
  File "/usr/lib/python3.7/site-packages/promnesia/__main__.py", line 261, in main
    install_server.install(args)
  File "/usr/lib/python3.7/site-packages/promnesia/misc/install_server.py", line 122, in install
    install_systemd(name=name, out=out, launcher=launcher, largs=largs)
  File "/usr/lib/python3.7/site-packages/promnesia/misc/install_server.py", line 77, in install_systemd
    raise e
  File "/usr/lib/python3.7/site-packages/promnesia/misc/install_server.py", line 70, in install_systemd
    systemd('stop' , unit_name, method=run) # ignore errors here if it wasn't running in the first place
  File "/usr/lib/python3.7/site-packages/promnesia/misc/install_server.py", line 54, in systemd
    'systemctl', '--no-pager', '--user', *args,
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl': 'systemctl'
```

It is obvious that it is trying to do systemd things, and while I don't exactly know what to expect `install-server` to do on a non-systemd machine, perhaps this can fail a bit nicer?

I see there is already some code for unsupported systems in `install_server.py`, maybe just non-systemd machines can fail the same way.

I can help with a PR if you give me some pointers here, this fix seems simple enough.

**Comment by karlicoss** [comment]
Thanks for reporting, yeah, this is a good point. Perhaps it could call `shutil.which("systemctl")` first (not sure if there is a more reliable way to detect Systemd), and if there is none, suggest to use Cron or something else, I mention it briefly in [setup guide](https://github.com/karlicoss/promnesia#setup).

Not sure about automatically adding to crontab, but chances are if the person is using a non-systemd distribution, they know about Linux enough to figure out their preferred way of autostarting anyway :)
