### ISSUE TITLE
Further Adventures

### ISSUE THREAD

**Issue by HalMorris** [karlicoss/promnesia#140]
After more reading, ran "promnesia serve" (somewhere you say to run "promnesia server", a typo I guess because serve works and server doesn't).  Did some stuff, including visiting the gwern site, and going around in circles hoping to see a green eye.  Got this log, including complaints about the nonexistence of this file, which I can confirm:
ls: cannot access '/home/hal/.local/share/promnesia/promnesia.sqlite': No such file or directory
(Note I am very serious and will put a lot into making this work, being a beta tester, with both programming background and philosophical interests that see to be like yours.  You can cut the bureaucracy and contact me at hal@panix.com

Serving on :13131...
[INFO    2020-09-19 22:07:51,769 promnesia server.py:129] url: https://www.gwern.net/
[INFO    2020-09-19 22:07:51,770 promnesia server.py:132] normalised url: gwern.net
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 947, in __call__
    raise exception
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 918, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 840, in call_function
    return self.interface(**parameters)
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 200, in visits
    where=lambda table, url: or_(
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 134, in search_common
    engine, binder, table = get_stuff()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 120, in get_stuff
    db_path = get_db_path()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 97, in get_db_path
    assert db.exists(), db
AssertionError: /home/hal/.local/share/promnesia/promnesia.sqlite
127.0.0.1 - - [19/Sep/2020 22:07:51] "POST /visits HTTP/1.1" 500 59
[DEBUG   2020-09-19 22:08:35,337 promnesia server.py:252] ['https://www.gwern.net/index', 'https://www.gwern.net/About', 'https://www.gwern.net/Links', 'https://www.gwern.net/Changelog', 'https://gwern.substack.com/', 'https://www.reddit.com/r/gwern/', 'https://www.patreon.com/gwern', 'https://www.gwern.net/tags/Silk-Road', 'https://www.gwern.net/tags/Bitcoin', 'https://www.gwern.net/tags/experiments', 'https://www.gwern.net/tags/DNB', 'https://www.gwern.net/Spaced-repetition', 'https://www.gwern.net/Faces', 'https://www.gwern.net/tags/newsletter', 'https://www.gwern.net/newsletter/2020/08', 'https://www.gwern.net/Sidenotes', 'https://www.gwern.net/newsletter/2020/07', 'https://www.gwern.net/newsletter/2020/05#gpt-3', 'https://www.gwern.net/newsletter/2020/06', 'https://www.gwern.net/GPT-3', 'https://www.gwern.net/Crops#hands', 'https://www.gwern.net/Holy-wars', 'https://www.gwern.net/newsletter/2020/05', 'https://www.gwern.net/Faces#danbooru2019e621-256px-biggan', 'https://www.gwern.net/Crops#danbooru2019-figures', 'https://www.gwern.net/newsletter/2020/04', 'https://www.gwern.net/GPT-2-music#generating-midi-with-10k30k-context-windows', 'https://www.gwern.net/#most-popular', 'https://www.gwern.net/Silk-Road', 'https://www.gwern.net/DNM-archives', 'https://www.gwern.net/DNM-arrests', 'https://www.gwern.net/Modafinil', 'https://www.gwern.net/LSD-microdosing', 'https://www.gwern.net/Zeo', 'https://www.gwern.net/DNB-FAQ', 'https://www.gwern.net/Death-Note-Anonymity', 'https://www.gwern.net/Complement', 'https://www.gwern.net/Google-shutdowns', 'https://www.gwern.net/Ads', 'https://www.thiswaifudoesnotexist.net/', 'https://www.gwern.net/TWDNE', 'https://www.gwern.net/Tanks', 'https://www.gwern.net/Self-decrypting-files', 'https://www.gwern.net/Archiving-URLs', 'https://www.gwern.net/Terrorism-is-not-about-Terror', 'https://www.gwern.net/The-Melancholy-of-Subculture-Society', 'https://www.gwern.net/#notable', 'https://www.gwern.net/Causality', 'https://www.gwern.net/Embryo-selection', 'https://www.gwern.net/Mail-delivery', 'https://www.gwern.net/Tool-AI', 'https://www.gwern.net/Complexity-vs-AI', 'https://www.gwern.net/Death-Note-script', 'https://www.gwern.net/The-Existential-Risk-of-Mathematical-Error', 'https://www.gwern.net/Iodine', 'https://www.gwern.net/The-Melancholy-of-Kyon', 'https://www.gwern.net/In-Defense-Of-Inclusionism', 'https://www.gwern.net/Bitcoin-is-Worse-is-Better', 'https://www.gwern.net/Sunk-cost', 'https://www.gwern.net/#statistics', 'https://www.gwern.net/Prediction-markets', 'https://www.gwern.net/Research-criticism', 'https://www.gwern.net/2012-election-predictions', 'https://www.gwern.net/Candy-Japan', 'https://www.gwern.net/Resorter', 'https://www.gwern.net/Google-Alerts', 'https://www.gwern.net/Order-statistics', 'https://www.gwern.net/Everything', 'https://www.gwern.net/docs/statistics/order/beanmachine-multistage/index.html', 'https://www.gwern.net/Milk', 'https://www.gwern.net/Hunter', 'https://www.gwern.net/hpmor#analysis', 'https://www.gwern.net/GoodReads', 'https://www.gwern.net/EA-donations', 'https://www.gwern.net/Statistical-notes', 'https://www.gwern.net/#cryptobitcoin', 'https://www.gwern.net/DNM-survival', 'https://www.gwern.net/Timestamping', 'https://www.gwern.net/#ai', 'https://www.gwern.net/Danbooru2019', 'https://www.gwern.net/Crops#danbooru2019-portraits', 'https://www.gwern.net/Coin-flip', 'https://www.gwern.net/Backstop', 'https://www.gwern.net/RNN-metadata', 'https://www.gwern.net/GPT-2', 'https://www.gwern.net/GPT-2-music', 'https://www.gwern.net/GPT-2-preference-learning', 'https://www.gwern.net/Hyperbolic-Time-Chamber', 'https://www.gwern.net/#cs', 'https://www.gwern.net/haskell/Summer-of-Code', 'https://www.gwern.net/The-3-Grenades', 'https://www.gwern.net/Turing-complete', 'https://www.gwern.net/haskell/Archiving-GitHub', 'https://www.gwern.net/Simulation-inferences', 'https://www.gwern.net/Choosing-Software', 'https://www.gwern.net/haskell/Run-Length-Encoding', 'https://www.gwern.net/haskell/Wikipedia-Archive-Bot', 'https://www.gwern.net/haskell/Wikipedia-RSS-Archive-Bot', 'https://www.gwern.net/Resilient-Haskell-Software', 'https://www.gwern.net/Evolutionary-Licenses', 'https://www.gwern.net/sicp/Introduction', 'https://www.gwern.net/sicp/Chapter-1.1', 'https://www.gwern.net/sicp/Chapter-1.2', 'https://www.gwern.net/sicp/Chapter-1.3', 'https://www.gwern.net/WiFi', 'https://www.gwern.net/AB-testing', 'https://www.gwern.net/#psychology', 'https://www.gwern.net/DNB-meta-analysis', 'https://www.gwern.net/Catnip', 'https://www.gwern.net/Catnip-survey', 'https://www.gwern.net/SMPY', 'https://www.gwern.net/Conscientiousness-and-online-education', 'https://www.gwern.net/Bakewell', 'https://www.gwern.net/Clone', 'https://www.gwern.net/Questions', 'https://www.gwern.net/Morning-writing', 'https://www.gwern.net/Cat-Sense', 'https://www.gwern.net/Replication', 'https://www.gwern.net/Hydrocephalus', 'https://www.gwern.net/Socks', 'https://www.gwern.net/#qs', 'https://www.gwern.net/Melatonin', 'https://www.gwern.net/zeo/Caffeine', 'https://www.gwern.net/zeo/Potassium', 'https://www.gwern.net/zeo/Redshift', 'https://www.gwern.net/zeo/Vitamin-D', 'https://www.gwern.net/zeo/ZMA', 'https://www.gwern.net/Wooden-pillows', 'https://www.gwern.net/Lunar-sleep', 'https://www.gwern.net/Nootropics', 'https://www.gwern.net/Creatine', 'https://www.gwern.net/Lithium', 'https://www.gwern.net/2014-spirulina', 'https://www.gwern.net/Melon', 'https://www.gwern.net/Lewis-meditation', 'https://www.gwern.net/Weather', 'https://www.gwern.net/Treadmill', 'https://www.gwern.net/Bacopa', 'https://www.gwern.net/#practical', 'https://www.gwern.net/Drug-heuristics', 'https://www.gwern.net/Search', 'https://www.gwern.net/Timing', 'https://www.gwern.net/Red', 'https://www.gwern.net/Improvements', 'https://www.gwern.net/Girl-Scouts-and-good-governance', 'https://www.gwern.net/plastination', 'https://www.gwern.net/Charity-is-not-about-helping', 'https://www.gwern.net/Console-Insurance', 'https://www.gwern.net/#politics', 'https://www.gwern.net/Terrorism-is-not-Effective', 'https://www.gwern.net/Slowing-Moores-Law', 'https://www.gwern.net/Littlewood', 'https://www.gwern.net/Colder-Wars', 'https://www.gwern.net/#philosophy', 'https://www.gwern.net/Language', 'https://www.gwern.net/Culture-is-not-about-Esthetics', 'https://www.gwern.net/The-Narrowing-Circle', 'https://www.gwern.net/Modus', 'https://www.gwern.net/Newton', 'https://www.gwern.net/Subscripts', 'https://www.gwern.net/Ontological-pantheism', 'https://www.gwern.net/An-Abortion-Dialogue', 'https://www.gwern.net/On-Disrespect', 'https://www.gwern.net/Justifications', 'https://www.gwern.net/Against-The-Miletians', 'https://www.gwern.net/Copyright', 'https://www.gwern.net/Immoral-Books', 'https://www.gwern.net/Isomorphisms', 'https://www.gwern.net/#fiction', 'https://www.gwern.net/fiction/The-Erl-King', 'https://www.gwern.net/fiction/The-Ones-Who-Walk-Towards-Acre', 'https://www.gwern.net/fiction/Missing-Cities', 'https://www.gwern.net/fiction/Men-of-Iron', 'https://www.gwern.net/fiction/Menard', 'https://www.gwern.net/fiction/How-the-Panther-got-Black', 'https://www.gwern.net/fiction/The-Palace-of-Wonders', 'https://www.gwern.net/fiction/Batman', 'https://www.gwern.net/fiction/Cloud-Nine', 'https://www.gwern.net/fiction/The-Last-Muezzin', 'https://www.gwern.net/fiction/Dinosaur-Comics', 'https://www.gwern.net/fiction/The-Buddhas-Wheel', 'https://www.gwern.net/fiction/Poems', 'https://www.gwern.net/fiction/Brave-poem', 'https://www.gwern.net/fiction/Dying-Outside', 'https://www.gwern.net/fiction/Genshiken', 'https://www.gwern.net/fiction/Safecracker', 'https://www.gwern.net/fiction/Hybrid-Rainbow', 'https://www.gwern.net/#literary-criticism', 'https://www.gwern.net/Story-Of-Your-Life', 'https://www.gwern.net/Dune-genetics', 'https://www.gwern.net/Suzanne-Delage', 'https://www.gwern.net/Scanners', 'https://www.gwern.net/fiction/The-Mulberry-Tree', 'https://www.gwern.net/fiction/The-Snowbanks-of-Time', 'https://www.gwern.net/#anime', 'https://www.gwern.net/Death-Note-Ending', 'https://www.gwern.net/MLP', 'https://www.gwern.net/Hafu', 'https://www.gwern.net/Arias-past-present-and-future', 'https://www.gwern.net/FMP-parody', 'https://www.gwern.net/komm-susser-tod', 'https://www.gwern.net/#docs', 'https://www.gwern.net/docs/radiance/2002-scholz-radiance', 'https://www.gwern.net/docs/xrisks/1985-hofstadter', 'https://www.gwern.net/docs/sociology/1987-rossi', 'https://www.gwern.net/docs/cs/1955-nash', 'https://www.gwern.net/docs/statistics/bayes/1994-falk', 'https://www.gwern.net/docs/bitcoin/2008-nakamoto', 'https://www.gwern.net/docs/bitcoin/2011-davis', 'https://www.gwern.net/docs/japanese/2002-gibson', 'https://www.gwern.net/docs/culture/2007-wolfe', 'https://www.gwern.net/docs/culture/1983-wolfe-thecitadeloftheautarch-thejustman', 'https://www.gwern.net/docs/culture/1963-asimov', 'https://www.gwern.net/docs/sr/2013-power', 'https://www.gwern.net/docs/bitcoin/2014-mccaleb', 'https://www.gwern.net/docs/rotten.com/library/index.html', 'https://www.gwern.net/docs/biology/2000-iapac-norvir/description.html', 'https://www.reddit.com/r/gwern/comments/aapn1l/okcupid_blog_archives/', 'https://www.gwern.net/docs/genetics/selection/www.mountimprobable.com/index.html', 'https://www.gwern.net/docs/philo/2010-richardson-bythenumbers-vectors30', 'https://www.gwern.net/Fulltext', 'https://www.gwern.net/#anime-docs', 'https://www.gwern.net/otaku', 'https://www.gwern.net/docs/eva/2002-takeda-notenkimemoirs', 'https://www.gwern.net/docs/eva/2010-crc', 'https://www.gwern.net/docs/eva/1996-animerica-conscience-otaking', 'https://www.gwern.net/docs/eva/2011-house', 'https://www.gwern.net/docs/eva/1996-newtype-anno-interview', 'https://www.gwern.net/docs/eva/1997-animeland-may-hideakianno-interview-english', 'https://www.gwern.net/docs/eva/1997-animeland-may-hideakianno-interview-french', 'https://www.gwern.net/docs/eva/2003-oshii-izubuchi', 'https://www.gwern.net/docs/eva/2003-rahxephoncomplete-anno-izubuchi', 'https://www.gwern.net/docs/eva/2004-okada', 'https://www.gwern.net/docs/eva/2005-murakami', 'https://www.gwern.net/docs/anime/1997-utena', 'https://www.gwern.net/docs/eva/2005-little-boy', 'https://www.gwern.net/docs/eva/2005-sawaragi', 'https://www.gwern.net/docs/anime/2010-sarrazin', 'https://www.gwern.net/#wikipedia', 'https://www.gwern.net/Wikipedia-and-Dark-Side-Editing', 'https://www.gwern.net/Wikipedia-and-Other-Wikis', 'https://www.gwern.net/Wikipedia-and-YouTube', 'https://www.gwern.net/Wikipedia-and-Knol', 'https://www.gwern.net/Wikipedia-resume', 'https://www.gwern.net/#personal', 'https://www.gwern.net/Notes', 'https://www.gwern.net/Epigrams', 'https://www.gwern.net/Book-reviews', 'https://www.gwern.net/Tea', 'https://www.gwern.net/Blackmail']
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 947, in __call__
    raise exception
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 918, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 840, in call_function
    return self.interface(**parameters)
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 257, in visited
    engine, binder, table = get_stuff()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 120, in get_stuff
    db_path = get_db_path()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 97, in get_db_path
    assert db.exists(), db
AssertionError: /home/hal/.local/share/promnesia/promnesia.sqlite
127.0.0.1 - - [19/Sep/2020 22:08:35] "POST /visited HTTP/1.1" 500 59
[INFO    2020-09-19 22:08:54,471 promnesia server.py:129] url: https://github.com/karlicoss/promnesia#how-does-it-work
[INFO    2020-09-19 22:08:54,472 promnesia server.py:132] normalised url: github.com/karlicoss/promnesia
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 947, in __call__
    raise exception
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 918, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 840, in call_function
    return self.interface(**parameters)
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 200, in visits
    where=lambda table, url: or_(
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 134, in search_common
    engine, binder, table = get_stuff()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 120, in get_stuff
    db_path = get_db_path()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 97, in get_db_path
    assert db.exists(), db
AssertionError: /home/hal/.local/share/promnesia/promnesia.sqlite
127.0.0.1 - - [19/Sep/2020 22:08:54] "POST /visits HTTP/1.1" 500 59
[INFO    2020-09-19 22:08:54,492 promnesia server.py:129] url: https://github.com/karlicoss/promnesia#how-does-it-work
[INFO    2020-09-19 22:08:54,492 promnesia server.py:132] normalised url: github.com/karlicoss/promnesia
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 947, in __call__
    raise exception
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 918, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 840, in call_function
    return self.interface(**parameters)
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 200, in visits
    where=lambda table, url: or_(
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 134, in search_common
    engine, binder, table = get_stuff()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 120, in get_stuff
    db_path = get_db_path()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 97, in get_db_path
    assert db.exists(), db
AssertionError: /home/hal/.local/share/promnesia/promnesia.sqlite
127.0.0.1 - - [19/Sep/2020 22:08:54] "POST /visits HTTP/1.1" 500 59
[INFO    2020-09-19 22:08:56,261 promnesia server.py:129] url: https://www.gwern.net/
[INFO    2020-09-19 22:08:56,262 promnesia server.py:132] normalised url: gwern.net
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 947, in __call__
    raise exception
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 918, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 840, in call_function
    return self.interface(**parameters)
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 200, in visits
    where=lambda table, url: or_(
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 134, in search_common
    engine, binder, table = get_stuff()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 120, in get_stuff
    db_path = get_db_path()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 97, in get_db_path
    assert db.exists(), db
AssertionError: /home/hal/.local/share/promnesia/promnesia.sqlite
127.0.0.1 - - [19/Sep/2020 22:08:56] "POST /visits HTTP/1.1" 500 59
[INFO    2020-09-19 22:08:56,266 promnesia server.py:129] url: https://www.gwern.net/
[INFO    2020-09-19 22:08:56,266 promnesia server.py:132] normalised url: gwern.net
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 947, in __call__
    raise exception
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 918, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 840, in call_function
    return self.interface(**parameters)
  File "/home/hal/.local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 200, in visits
    where=lambda table, url: or_(
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 134, in search_common
    engine, binder, table = get_stuff()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 120, in get_stuff
    db_path = get_db_path()
  File "/home/hal/.local/lib/python3.7/site-packages/promnesia/server.py", line 97, in get_db_path
    assert db.exists(), db
AssertionError: /home/hal/.local/share/promnesia/promnesia.sqlite
127.0.0.1 - - [19/Sep/2020 22:08:56] "POST /visits HTTP/1.1" 500 59

**Comment by karlicoss** [comment]
Hi! Sorry again for late response..

So it can't find the index `/home/hal/.local/share/promnesia/promnesia.sqlite`. Most likely you've set `OUTPUT_DIR` in your `config.py`, but didn't pass it as `--db` argument to `promnesia serve`:

https://github.com/karlicoss/promnesia/blob/b0c738614abb7e87f9461b6ecb8e750186f1625b/doc/config.py#L96-L99

You can either:
- comment it out in `OUTPUT_DIR` (and rerun `promnesia index`)
- or run `promnesia server --db /path/to/your/db/in/config`

Let me know if this helps!

**Comment by karlicoss** [comment]
closing to clear out of the way since tools for troubleshooting are now better, but feel free to reopen
