### ISSUE TITLE
mac setup breaks because of unmet dependency (no module named 'zoneinfo')

### ISSUE THREAD

**Issue by obh** [karlicoss/promnesia#262]
I was trying the setup from the repo on my mac, and it broke when I ran the script `./scripts/promnesia` because of unmet dependency. 
Installing the dependency fixed this issue `pip3 install backports.zoneinfo`

```
➜  promnesia git:(master) ./scripts/promnesia
.....
  warnings.warn("You might want to install 'logzero' for nice colored logs!")
[ERROR   2021-12-13 17:48:48 promnesia common.py:499] cannot import name 'zoneinfo' from 'backports' (/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/backports/__init__.py)
Traceback (most recent call last):
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/pytz_deprecation_shim-0.1.0.post0-py3.8.egg/pytz_deprecation_shim/_compat_py3.py", line 5, in <module>
    import zoneinfo
ModuleNotFoundError: No module named 'zoneinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohitsharma/learning/browser/promnesia/src/promnesia/common.py", line 490, in get_system_zone
    import tzlocal
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/tzlocal-4.1-py3.8.egg/tzlocal/__init__.py", line 10, in <module>
    from tzlocal.unix import get_localzone, get_localzone_name, reload_localzone
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/tzlocal-4.1-py3.8.egg/tzlocal/unix.py", line 6, in <module>
    import pytz_deprecation_shim as pds
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/pytz_deprecation_shim-0.1.0.post0-py3.8.egg/pytz_deprecation_shim/__init__.py", line 16, in <module>
    from . import helpers
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/pytz_deprecation_shim-0.1.0.post0-py3.8.egg/pytz_deprecation_shim/helpers.py", line 5, in <module>
    from . import _common, _compat
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/pytz_deprecation_shim-0.1.0.post0-py3.8.egg/pytz_deprecation_shim/_compat.py", line 6, in <module>
    from . import _compat_py3 as _compat_impl
  File "/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/pytz_deprecation_shim-0.1.0.post0-py3.8.egg/pytz_deprecation_shim/_compat_py3.py", line 7, in <module>
    from backports import zoneinfo
ImportError: cannot import name 'zoneinfo' from 'backports' (/Users/rohitsharma/Library/Python/3.8/lib/python/site-packages/backports/__init__.py)
[ERROR   2021-12-13 17:48:48 promnesia common.py:500] Couldn't determine system timezone. Falling back to UTC. Please report this as a bug!
ERROR: Please specify a mode
```

**Comment by purarue** [comment]
May be related to [this recent issue](https://github.com/karlicoss/promnesia/issues/253)

**Comment by karlicoss** [comment]
yeah, not sure how to help, the only OSX hosts I have are CI hosts, and they seem to pass :) 
I guess we can keep it open in case anyone else encounters this
