### ISSUE TITLE
Error when creating the initial database `'tuple' object has no attribute 'isoformat`

### ISSUE THREAD

**Issue by adulau** [karlicoss/promnesia#272]
When doing `promnesia create`, I got the error below. I tried with the PyPI distribution and also the `master` branch of the repository.

~~~
Traceback (most recent call last):
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1647, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 465, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/types.py", line 627, in process
    return process_param(value, dialect)
  File "/home/adulau/.local/lib/python3.8/site-packages/cachew/__init__.py", line 98, in process_bind_param
    iso = value.isoformat()
AttributeError: 'tuple' object has no attribute 'isoformat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adulau/.local/bin/promnesia", line 8, in <module>
    sys.exit(main())
  File "/home/adulau/.local/lib/python3.8/site-packages/promnesia/__main__.py", line 386, in main
    do_index(
  File "/home/adulau/.local/lib/python3.8/site-packages/promnesia/__main__.py", line 95, in do_index
    errors = list(_do_index(dry=dry, sources_subset=sources_subset, overwrite_db=overwrite_db))
  File "/home/adulau/.local/lib/python3.8/site-packages/promnesia/__main__.py", line 80, in _do_index
    dump_errors = visits_to_sqlite(it(), overwrite_db=overwrite_db)
  File "/home/adulau/.local/lib/python3.8/site-packages/promnesia/dump.py", line 88, in visits_to_sqlite
    conn.execute(table.insert().values(bound))
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1445, in execute
    return Connection.executors[c](
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1579, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1649, in _execute_context
    self._handle_dbapi_exception(e,
  File "/home/adulau/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1837, in _handle_dbapi_exception
    raise exc.DBAPIError.instance(
sqlalchemy.exc.StatementError: 'tuple' object has no attribute 'isoformat' (original cause: AttributeError: 'tuple' object has no attribute 'isoformat') 'INSERT INTO visits (norm_url, orig_url, dt, locator_title, locator_href, src, context, duration) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' []
~~~

I supposed it was due to the recent changes of pytz library, but those are the latest ones install

~~~shell
13:06 $ pip3 list | grep tz
pytz                              2021.3
pytz-deprecation-shim             0.1.0.post0
tzdata                            2021.5
tzlocal                           4.1
~~~

**Comment by karlicoss** [comment]
thanks for reporting!
hmm, that's odd -- could you please post the full command you're running? (`promnesia create` doesn't exist, not sure if it was `promensia config create` or something else)
also could you attach versions for sqlalchemy and cachew as well please? (`pip3 list --user | egrep -i 'cachew|alchemy'`)

**Comment by adulau** [comment]
Indeed, it was `promnesia index` sorry I did a typo.  Thanks for the SQLAlchemy hint.

I just solved by upgrading SQLAlchemy to the latest version. 

`pip3 install --upgrade SQLAlchemy`

Maybe the archive of the issue might be useful for people having an older version of SQLAlchemy installed too. I'll close the issue. Thanks for this awesome piece of software.

**Comment by karlicoss** [comment]
ah nice glad it worked for you now!
if you still can dig what version of sqlalchemy you used to have, this would be helpful -- it might mean I need to set the minimum version requirements in promnesia, or handle some older API to make it compatible with older version :)

**Comment by adulau** [comment]
Don't ask me why I had a so old version of SQLAlchemy (0.7.10), but it worked with 1.4.31. 

```
    Found existing installation: SQLAlchemy 0.7.10
    Uninstalling SQLAlchemy-0.7.10:
      Successfully uninstalled SQLAlchemy-0.7.10
Successfully installed SQLAlchemy-1.4.31
```
