### ISSUE TITLE
promnesia config create error

### ISSUE THREAD

**Issue by imargonis** [karlicoss/promnesia#396]
When I run 'promnesia config create' I get the following error:

Traceback (most recent call last):
  File "/home/imargonis/.local/bin/promnesia", line 5, in <module>
    from promnesia.__main__ import main
  File "/home/imargonis/.local/lib/python3.10/site-packages/promnesia/__main__.py", line 13, in <module>
    from . import server
  File "/home/imargonis/.local/lib/python3.10/site-packages/promnesia/server.py", line 147, in <module>
    class Where(Protocol):
  File "/home/imargonis/.local/lib/python3.10/site-packages/promnesia/server.py", line 148, in Where
    def __call__(self, table: Table, url: str) -> ColumnElement[bool]:
TypeError: 'VisitableType' object is not subscriptable

**Comment by imargonis** [comment]
I updated my python version and it worked.
