### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Klaudioz** [karlicoss/promnesia#84]
I can't see what I'm doing wrong.

```
klaudioz@wsb-server:~$ git clone https://github.com/karlicoss/promnesia.git
Cloning into 'promnesia'...
remote: Enumerating objects: 172, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 5028 (delta 85), reused 93 (delta 54), pack-reused 4856
Receiving objects: 100% (5028/5028), 1017.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3573/3573), done.
klaudioz@wsb-server:~$ cd promnesia/
klaudioz@wsb-server:~/promnesia$ 
klaudioz@wsb-server:~/promnesia$ cp config.py.example config.py
klaudioz@wsb-server:~/promnesia$ 
klaudioz@wsb-server:~/promnesia$ ./scripts/promnesia demo --port 13131 --config config.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/klaudioz/promnesia/src/promnesia/__init__.py", line 2, in <module>
    from .common import PathIsh, Visit, Source, last
  File "/home/klaudioz/promnesia/src/promnesia/common.py", line 31
    title: str
         ^
SyntaxError: invalid syntax
klaudioz@wsb-server:~/promnesia$ python3 -V
Python 3.5.3

**Comment by karlicoss** [comment]
Hi, you're doing nothing wrong, but the python version is old, it doesn't support `python3.5`. 
Any chance you can try on `3.6` or later? 
I generally try to support old versions as long as feasible, but `3.5` is missing way too many nice features, and its popularity only dwindling, so unlikely this project will ever support it :(

**Comment by Klaudioz** [comment]
It's working now. Thanks for your help.

**Comment by karlicoss** [comment]
Awesome! I'll add the version restriction to setup.py, so the error won't be so cryptic anymore. Let me know in case you have other issues, happy to help
